### ISSUE TITLE
[Feature reques] [QOL] Button combo to enter application directory

### ISSUE THREAD

**Issue by fennectech** [switchbrew/nx-hbmenu#104]
I would like a button combo to enter an applications directory instaid of launching it.  I have edizon.nro edizon_beta.nro and edizon_test.nro all in one directory   I would like a keycombo that would let me get into a directory with an nro in it.

**Comment by yellows8** [comment]
Just store the other NROs elsewhere?("/switch/" / whatever)

**Comment by yellows8** [comment]
Just rename {name}.nro for "{name}/{name}.nro" to something else (edizon.nro -> edizon_release.nro / whatever), the directory would then be displayed.
