### ISSUE TITLE
2168-0002 (0x4a8)

### ISSUE THREAD

**Issue by BNWEIN** [switchbrew/nx-hbmenu#106]
Hi.

I am regularly getting the above message, when doing lots of different actions. One that is easy to repeat is going to the HB App Store, then clicking on Retro Arch, and then trying to download. 2 seconds into the download i get the error above.

Crash Report:  https://gist.github.com/BNWEIN/7fc066ab9f19acc4a057a4eebf53c1d2

**Comment by fincs** [comment]
"HB App Store" is not supported due to hostilities with the developers of said unofficial project.
