### ISSUE TITLE
Bug: Black Screen, Freezes if using Ipathed switch Firmware 4.1.0 to access Homebrew menu

### ISSUE THREAD

**Issue by unholyhimura** [switchbrew/nx-hbmenu#110]
Hello,

I have an Ipatched switch on firmware 4.1.0 and was trying to open Homebrew menu using latest version of Atmosphère 0.10.1.

Using Atmosphere 0.94 I had no issue but when I updated to latest version 10.1 the Homebrew menu became unstable. It will freeze, give black screen.

Atmosphère 0.9.4 is bundled with hbl 2.2, and hbmenu 3.1.1.
Atmosphère 0.10.1 is bundled with hbl 2.3, and hbmenu 3.2.0.

Obs.: I've tried files from hbl 2.2, and hbmenu 3.1.1 in Atmosphère 0.10.1 and had same results.

Solution was to upgrade my emuMMC to 8.1.0 and now Homebrew is working (holding R, album, ...) without any black screen.

Look like it's a combination between Atmosphère & nx-hbmenu when on firmware 4.1.0. I dont know if ipatched makes any difference but this is my current device.

I've opened a ticket on Kosmos repository as well and they instructed me to open it here. Please take a look at their response here: [https://github.com/AtlasNX/Kosmos/issues/263](url)

**Comment by SciresM** [comment]
Not a hbmenu problem. This was fixed in https://github.com/Atmosphere-NX/Atmosphere/commit/0a18c63f245d2dbf38cd966e6f40ef20396ae41f.
