### ISSUE TITLE
Can't used the joy cons/controller

### ISSUE THREAD

**Issue by LadyHaywood** [switchbrew/nx-hbmenu#111]
I'm on the latest update but it'll only let me use the touch screen to navigate. I tried as an nro before converting it to an nsp, neither of them worked.

**Comment by yellows8** [comment]
"converting it to an nsp" ....don't

Dup of #108?

**Comment by LadyHaywood** [comment]
The nsp worked fine, I just couldn't move with a controller/joy con. I got it to work after restarting the system. I found someone saying all you need to do is repair them to the switch but that didn't work for me.
