### ISSUE TITLE
nx-hbmenu won't see any apps on my SD

### ISSUE THREAD

**Issue by evelynmatson** [switchbrew/nx-hbmenu#114]
Hello! This is a repeat of #36.

Does anyone have any other suggestions if what was suggested there doesn't work? I'm on macOS and have done sudo chflags -R arch switch from within the switch sd card volume, then sudo dot_clean -mn /Volumes/SWITCH. I even went into Hekate and did unset archive bit. Homebrew still shows nothing.

If it's helpful, I managed to open NX-shell and tried to go into the switch folder, and it shows nothing there (not even 'parent folder'!). The permissions on the switch folder looked different from the atmosphere folder when I checked on NX-Shell, but when I put the SD card back on my mac to try and change that they both had permissions wide open. I'm also getting a "fswrite nx-shell lastdir failed 202" kind of error from NX-Shell each time I try to open a directory in it, but after tapping ok it opens just fine.

Specifically, the 'switch' folder shows permissions '-rw-rw-rw-' in NX-Shell. Not a directory?? Whaaaat? It still lets me browse into it, but that may explain some of why it shows as empty inside. Again, it isn't like that when I look at the permissions from macOS.

**Comment by yellows8** [comment]
No need for a dup.
