### ISSUE TITLE
How create code for custom Icons?

### ISSUE THREAD

**Issue by Klauserus** [switchbrew/nx-hbmenu#117]
Hi I know you keep a very accurate list of how to change the appearance of nx Hbmenu. But unfortunately I am not a json programmer and don't quite get through. Please help me with my cfg. for example: I packed folder_icon. png into a romsf. I put this "icon. romfs" data into the theme folder on the SD where the cfg files are located.

 Code looks like this: Unfortunately the whole theme will not work anymore. 
};

assets={
    battery_icon={
        path = "/battery_icon.png";
        imageSize = (16,16);
    };

    // Any other objects here.

assets={
    folder_icon={
        path = "/folder_icon.png";
        imageSize = (256,256);
    };

    // Any other objects here.

};

i unterstand your text so, that asset location is in the romfs data not the SD:/config/nx-hbmenu/themes/ location. But how can i hint the program so take the romfs?

thx and thx for your hard work on nx-hbmenu

**Comment by yellows8** [comment]
Path is relative to `"{mount-name}:/"`, so the path should not start with "/".

```
assets={
    battery_icon={
        path = "battery_icon.png";
        imageSize = (16,16);
    };

    folder_icon={
        path = "folder_icon.png";
        imageSize = (256,256);
    };
};
```

**Comment by Klauserus** [comment]
thx, but it doesnt work. Theme is stable but no changes in folder or battery icon.

I copyed your code and overrite mine.

takes nx-hbmenu the romfs automaticly from /config/nx-hbmenu/themes?

i make romfs with romfs builder from gbatemp.

thx

**Comment by yellows8** [comment]
"/config/nx-hbmenu/themes" yes

So you can select it fine from the Theme Menu, but the displayed gfx are the same?

**Comment by Klauserus** [comment]
the colors are changed how i like it. but the graphics not.

here the full code

themeInfo={
    name="New One";
    author="Test";
    version="1.0.0";
};

lightTheme={
    textColor=(0,0,0,255);
    frontWaveColor=(147,112,219,255);
    middleWaveColor=(238,89,89,1);
    backWaveColor=(110,52,226,255);
    backgroundColor=(253,140,140,255);
    highlightColor=(254,124,1,1);
    separatorColor=(128,0,128,255);
    enableWaveBlending=0;
};

darkTheme={
    textColor=(255,255,255,255);
    frontWaveColor=(75,157,188,1);
    middleWaveColor=(93,166,194,1);
    backWaveColor=(65,145,176,1);
    backgroundColor=(254,124,1,1);
    highlightColor=(254,124,1,1);
    separatorColor=(240,132,0,1);
    enableWaveBlending=0;
};

layout={
    backWave={
        visible=true;
        posType=false;
        size = (1);
    };

    // Any other objects here.
    
};

assets={
    battery_icon={
        path = "battery_icon.png";
        imageSize = (16,16);
    };

    folder_icon={
        path = "folder_icon.png";
        imageSize = (256,256);
    };
};

here are the files: https://easyupload.io/vqm387

**Comment by yellows8** [comment]
Use the cmd-line tool as doc'd on the wiki, not {GUI tool} - the RomFs can't include the IVFC.

**Comment by Klauserus** [comment]
Good Evening

i build it now with devkitpro without gui. 

This File comes out: https://easyupload.io/6am74g

Code are the same. I put the romfs file into /config/nx-hbmenu/themes/. But nothing change. I see no ather icons for folders.

What i am doing wrong?

thanks for help

**Comment by yellows8** [comment]
Your .cfg filename is wrong. `The .romfs (and therefore the input directory) contains: '/theme.cfg', ...`

**Comment by Klauserus** [comment]
Oh thanks. I works.

Theme Red is for your page if you like. And Theme AC i cant set a background image. Time to another theme build lessen :) please. https://easyupload.io/dvjf7k

Code:
layout={
    backWave={
        visible=true;
        posType=false;
        size = (1);
    };

    backgroundImage={
        visible=true;
        posType=true;
        posStart=(0,0) ;
    };
    
};

assets={
    battery_icon={
        path = "battery_icon.png";
        imageSize = (32,32);
    };

    folder_icon={
        path = "folder_icon.png";
        imageSize = (256,256);
    };

    background_image={
        path = "background_image.png";
        imageSize = (1280,720);

};

I am not a Programmer ^^

i wish you a nice easter

**Comment by yellows8** [comment]
FWIW color values must be 0-255, not float values like `0.8`. If you want to actually change the size for *Wave, use `size = (0,{VALUE});`, otherwise don't include that field. Not sure @ background-image, will have to test it later.

If you want, themes can be added here: https://switchbrew.org/wiki/Homebrew_Themes (do not use upload-hosting which expires for that)

**Comment by Klauserus** [comment]
I hope i understand you right. I delete the backwave color code in my cfg, but i cant see a background picture.
};

darkTheme={
    textColor=(255,255,255,255);
    frontWaveColor=(231,222,241,1);
    middleWaveColor=(154,185,167,1);
    backWaveColor=(105,140,110,1);
    backgroundColor=(232,188,142,1);
    highlightColor=(254,124,1,1);
    separatorColor=(240,132,0,1);
    enableWaveBlending=0;
};

assets={
    battery_icon={
        path = "battery_icon.png";
        imageSize = (32,32);
    };

    background_image={
        path = "background_image.png";
        imageSize = (1280,720);
    };

    folder_icon={
        path = "folder_icon.png";
        imageSize = (256,256);
    };

    invalid_icon={
        path = "invalid_icon.png";
        imageSize = (256,256);
    };

    theme_icon_dark={
        path = "invalid_icon_dark.png";
        imageSize = (256,256);
    };

    theme_icon_light={
        path = "invalid_icon_light.png";
        imageSize = (256,256);
    };

};

**Comment by yellows8** [comment]
I meant layout.backWave.size. layout.backgroundImage has to exist otherwise it won't be displayed. And did you really intend to use alpha=1?

I tried your AC theme and it seems to be failing to load the config - Theme Menu displays the defaults for the theme, and selecting has no affect gfx-wise. Is that what happens for you?

**Comment by Klauserus** [comment]
I rewrited the code and now it works but backgroundimage wont.
I maked a screenshot and take it into the zip file with the theme.romfs.
Alpha=1? are you mean the alpha channel in Pictures? i dont have save the alpha channel in the pictures, i belive.

please look at the code

thanks for your patience

Link: https://easyupload.io/wyfwiw

**Comment by yellows8** [comment]
Was referring to `frontWaveColor=(231,222,241,1);`, etc. layout.backgroundImage is wrong, hopefully this fixed config works (haven't tested it): https://gist.github.com/yellows8/1e37fa4d4cf191a0b2f439ebe59985d8

**Comment by Klauserus** [comment]
it works. Thanks a lot.

**Comment by Corgano** [comment]
I don't know if i should reply here or the other thread.

I'm using the above sample you provided, but am having issues getting it to work. Does it NEED to be formatted as romfs in order to have assets? Is there any way i can have just the theme.cfg and background.jpg in the themes folder, and have it use the jpg as the background?

**Comment by Corgano** [comment]
I'm going to reply to the new thread instead
