### ISSUE TITLE
Hbmenu Crashing

### ISSUE THREAD

**Issue by Lost0Neko** [switchbrew/nx-hbmenu#119]
Hello,

I have an issue with the Hbmenu.
It crashes when i load up the homenbrew Ultimate Mod Manager using the App Ssbu.
It works fine if i boot the same homebrew, but instead of using Smash as an App, i used Youtube, and it worked.

I tested if i could open other Homebrew work, and all other homebrews i have do work.

I added the crash logs.

[00881365521_01006a800016e000.log](https://github.com/switchbrew/nx-hbmenu/files/4545551/00881365521_01006a800016e000.log)

**Comment by fincs** [comment]
Sounds like a problem with the homebrew app in question, not hbmenu. Also, hbmenu is just a graphical frontend for the real piece of software that is responsible for loading homebrew, that is, hbloader.

**Comment by yellows8** [comment]
@Lost0Neko When *exactly* does the crash occur? Boot -> hbmenu -> launch app -> crash?(Before the launched app displays anything?) Other apps when launched with Smash running work fine, right?(Make sure you're running least clean AMS without custom-sysmodules too)

If there's a .jpg for this crash-report available, upload that too.
