### ISSUE TITLE
Touch-screen support

### ISSUE THREAD

**Issue by yellows8** [switchbrew/nx-hbmenu#12]
Touch-screen should be supported for icon selection + {launch/folder-open}.

**Comment by ihatetothink** [comment]
I'm tackling this, for now I have scrolling through the files almost working. How should we allow the user to launch de hb/open the folder? an extra button or just pressing the big image? I have the feeling that the latter might not be really intuitive without some indication

**Comment by yellows8** [comment]
Latter, maybe allow doing that via touching the current small-icon again too.

**Comment by ihatetothink** [comment]
@StevenMattera PR looks better than what I did, leaving this to him

**Comment by yellows8** [comment]
00e96fd53b8e738c12af641594086e594dde4ac9
