### ISSUE TITLE
How can I install nx-hbmenu?

### ISSUE THREAD

**Issue by dessertforks** [switchbrew/nx-hbmenu#122]
I put the nx-hbmenu.nro in the root folder of TF card.
Then I can not find it in album of the machine.
How?

**Comment by TYBACKzz1** [comment]
Open

**Comment by TYBACKzz1** [comment]
Open

**Comment by HookedBehemoth** [comment]
The filename expected by hbloader is "hbmenu.nro".
Remove the leading "nx-".

**Comment by MaqsoodHaidary** [comment]
is this only for patched version?

**Comment by Masamune3210** [comment]
No? You don't install this. It comes with atmos so you in general shouldn't even have to mess with the file at all
