### ISSUE TITLE
Does not show icon.jpg on sideloaded .nro

### ISSUE THREAD

**Issue by iUltimateLP** [switchbrew/nx-hbmenu#123]
Hey, when developing a homebrew app I recognized that the icon.jpg is not shown in the hbmenu (and instead a switch with an exclamation mark) when transferring it either via nxlink or placing the .nro on the SD card? Is that a bug or a mistake from my side? I do have a icon.jpg placed next to the makefile and also set the path in the makefile.

Thanks!

**Comment by yellows8** [comment]
<https://github.com/switchbrew/nx-hbmenu#credits> ` This library doesn't ...`

**Comment by iUltimateLP** [comment]
Hmm it's a totally normal .jpg I saved in Photoshop, and since when was JPG ever lossless? Strange...

**Comment by yellows8** [comment]
aka "progressive"

**Comment by iUltimateLP** [comment]
Turned it off, still the same issue. Here's the .jpg I use, if that helps.
![icon2](https://user-images.githubusercontent.com/8491339/81957845-6fa44800-960d-11ea-8261-19044a130b3e.jpg)

**Comment by yellows8** [comment]
It needs to be 256x256 <https://github.com/switchbrew/nx-hbmenu/blob/master/icon.jpg>

**Comment by iUltimateLP** [comment]
Thanks, that was it 👍

**Comment by yellows8** [comment]
Btw using fsInitialize/fsExit from an app is not needed, it's done automatically...(see fs/ examples)

Isn't capsaLoadAlbumFile/{caps*} usable for your use-case, instead of manually accessing Bis?

**Comment by iUltimateLP** [comment]
Thanks for the tip.

It would be usable, but there is no real advantage in copying over the data from capsaLoadAlbumFile into a buffer and then send it along the socket if the files are present (other than it might be more performant than finding the filenames right now since I haven't figured the game ID encryption in the screenshot filename out yet).

**Comment by yellows8** [comment]
caps* is the proper way to access it though, and you're already using capsa anyway...
