### ISSUE TITLE
Problems with FAT32

### ISSUE THREAD

**Issue by DeltaPhoxtrot** [switchbrew/nx-hbmenu#125]
Whenever I try to install atmosphere onto my Switch using an SD card formatted from exFAT to FAT32, my Switch never detects the games on the Nintendo folder. Nothing on there is more than 4GB after a suggestion from someone else I asked. Also, hbmenu doesn't detect my Switch folder on the same SD card after converting it to FAT32.

**Comment by fincs** [comment]
Potential duplicate of:

https://github.com/switchbrew/nx-hbmenu/issues/81
https://github.com/switchbrew/nx-hbmenu/issues/63
https://github.com/switchbrew/nx-hbmenu/issues/36

Check your archive bits on your folders (as they make HOS think the folders are a giant file).

**Comment by DeltaPhoxtrot** [comment]
Thank you you're a godsend!! I'm sorry for making a duplicate issue and wasting your time but this worked and solved all my issues! It was specifically thread 63 that helped me if anyone else is having a similar issue!
I'm closing the thread now. Again, thank you!
