### ISSUE TITLE
I can't see the install button

### ISSUE THREAD

**Issue by JinguLan** [switchbrew/nx-hbmenu#126]
I set the DNS right and get to the ctest.cdn.nintendo.net. But it shows white screen and I can't see the install button

**Comment by JinguLan** [comment]
I've tried two versions. 3.3.0 and 3.0.0

**Comment by fincs** [comment]
What do you mean by "install button"? This is the Homebrew Menu...

**Comment by JinguLan** [comment]
> What do you mean by "install button"? This is the Homebrew Menu...

isn't it homebrew launcher?

**Comment by fincs** [comment]
No, it's the Homebrew Menu (or hbmenu for short).

**Comment by JinguLan** [comment]
sorry about disturbing

**Comment by Dafa95** [comment]
I have the same problem and I am not the only one, i searched and searched and I can not find the launcher..

**Comment by fincs** [comment]
There is no such thing as "Homebrew Launcher" on Switch. The following two components exist, though:

- Homebrew Loader (`hbloader` or `hbl` for short): This is the host process responsible for dynamically loading homebrew NROs and implementing the [Homebrew ABI](https://switchbrew.org/wiki/Homebrew_ABI), as well as some other miscellaneous bookkeeping. This component is not user visible.
- Homebrew Menu (`hbmenu` for short): This is the graphical shell that first runs when hbl starts up - this very repo contains the source code for it. This graphical shell is responsible for presenting a list of homebrew applications to the user, and instructing hbl which NRO to load next.

Installing homebrew is just a matter of copying (either manually or through nxlink) a NRO to the switch folder inside the SD card.

**Comment by Conan179** [comment]
@fincs Could it be that Dafa95 is looking for a forwarder?

**Comment by fincs** [comment]
There are no such things as "forwarders" in the supported homebrew environment. Anyone claiming to have or distribute them are in fact encouraging users to set up warez loading mechanisms, all which involve massive risks of banning the console and are considered severely damaging to the homebrew ecosystem. As such we heavily discourage their usage and offer absolutely no support whatsoever to anyone attempting to create, use or distribute them.

**Comment by Conan179** [comment]
I mean a icon on thy switch apps, to start hbmenu.

**Comment by fincs** [comment]
Custom "icons" on the Switch's main menu are technologically indistinguishable from pirated games. Please reread my reply.
