### ISSUE TITLE
Last HB Menu break theme

### ISSUE THREAD

**Issue by chronoss09** [switchbrew/nx-hbmenu#144]
I create many hb menu theme and someone told to me the last hb menu break all theme, the layout and icone work but no background. How to fix that please ?

**Comment by yellows8** [comment]
Link to the theme data?

**Comment by chronoss09** [comment]
https://www.reddit.com/r/NXThemes/comments/nuyw1j/hbmenu_theme_by_chronoss/hkgqv3h/?context=3

**Comment by yellows8** [comment]
Specifically which one of those?

**Comment by chronoss09** [comment]
All theme don't work, the layout work but no background on the theme... You can test one theme and the see what apening...

**Comment by yellows8** [comment]
The Splatoon 2 one works fine here (besides black-text on dark-section of background).

**Comment by chronoss09** [comment]
Can u test other theme please : https://www.reddit.com/user/chronoss09/

On my switch, i teste all SONY console theme and no background...

**Comment by yellows8** [comment]
The `path` in `background_image` for `PlayStation 2 Fat by Chronoss` is wrong, remove the `./`.

**Comment by chronoss09** [comment]
Ok but why before it working and now, with the update it don't work... i thing the new version of hb menu fix this error...

**Comment by yellows8** [comment]
Fix your themes.

physfs is used for loading themes, on older versions stdio was directly used.
