### ISSUE TITLE
App Store cannot connect to internet

### ISSUE THREAD

**Issue by Ryuhouji** [switchbrew/nx-hbmenu#145]
I wasn't sure where to get support for this, so I'll start here. I just installed this nro version on my switch, and when I launch it, it immediately says "Couldn't connect to the Internet!" The system settings internet options are saying connection is successful, and the nxthemes store is working just fine while browsing and downloading themes from the internet, so my switch definitely has a connection.

**Comment by fincs** [comment]
This is clearly an issue with the third party application, not hbmenu. Please keep in mind that the service you're referring to is not affiliated with switchbrew.

**Comment by Ryuhouji** [comment]
I don't understand, I downloaded the app's nro from this github page, how is it not related

**Comment by fincs** [comment]
This GitHub repo is for the Switch Homebrew Menu, which is hosted here. You're probably thinking of a different GitHub repo.

**Comment by Ryuhouji** [comment]
Yes, the hbmenu is what's unable to connect.

**Comment by fincs** [comment]
I'm sorry, but hbmenu does not connect to the internet at all, nor does it display a "Couldn't connect to the Internet!" message. You seem to be confusing hbmenu with a different application altogether that has nothing to do with hbmenu.

**Comment by Ryuhouji** [comment]
Oh, i see, I was looking at the github for the actual menu, not the app store. In my defense they look similar unless you really pick out the semantics... and github doesn't (does?) do a great job of making things stick out.
