### ISSUE TITLE
I'm trying to install hbmenu.nro and I keep getting error code 2110-3127

### ISSUE THREAD

**Issue by Liljesus420** [switchbrew/nx-hbmenu#152]

**Comment by fincs** [comment]
What did you exactly do here? hbmenu comes bundled with Atmosphère, there is no need to "install" anything.

**Comment by Liljesus420** [comment]
Download latest [nx-hbmenu](https://github.com/switchbrew/nx-hbmenu/releases/latest).
Put the hbmenu.nro on the root of your sdcard.
Insert the sdcard into the device.
Set your Switch DNS server to 104.236.106.125, and perform a connection test.

**Comment by Masamune3210** [comment]
Last part has absolutely nothing to do with hbmenu....
