### ISSUE TITLE
[Feature request]  Hide specific apps when in applet mode

### ISSUE THREAD

**Issue by fennectech** [switchbrew/nx-hbmenu#153]
Id like to be able to mark apps as hidden while in applet mode.  There are lots of apps that dont work in applet mode and it would be nice to just not have to scroll past them in applet mode.   It would be neat if you could mark them as hidden in addition to being able to mark apps as favorite

**Comment by yellows8** [comment]
You can move apps to a sub-directory under `/switch/` if you want.

"mark apps as favorite" That's the "Star" button.
