### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Chriclercrap** [switchbrew/nx-hbmenu#156]
Whenever i try to connect to the internet after i put the dns thing in the primary dns i get an error called Unable to connect to the internet

Could not perform DNS nam resolution. Please try again later. :(

**Comment by Chriclercrap** [comment]
Btw the hombrew menu thing is on the root of my sd card

**Comment by Masamune3210** [comment]
hbmenu has nothing to do with DNS servers, if you want to use one to block connecting to Nintendo, finding one that works and setting your console up to use it is out of scope and something you have to do on your own

**Comment by Chriclercrap** [comment]
ok thanks.
