### ISSUE TITLE
Error 2160-8007

### ISSUE THREAD

**Issue by napier2022** [switchbrew/nx-hbmenu#158]
I am unable to get Homebrew to install once I add the new DNS numbers- I go to test connection and get the error 2160-8007 "unable to connect" with no option to install Homebrew coming up. I had an issue with the DNS starting with 104 even being accepted, but found a different one that at least got me past that part.

**Comment by Masamune3210** [comment]
This has nothing to do with hbmenu, in fact, at this point, hbmenu hasn't even had a chance to try to run. You will have to figure out your DNS issues somewhere else unfortunately

**Comment by napier2022** [comment]
What I've read so far suggests I am past the DNS issue, and now Homebrew should be starting up, but it just isn't happening. If it's beyond the scope here that's fine but a recommendation of where else to troubleshoot or look for troubleshooting would be great. I have a pre-patch Switch, am using a clean micro SD card with the homebrew menu downloaded from here loaded on. Thank you.

**Comment by yellows8** [comment]
Out-of-scope indeed, see whatever repo you're using to launch hbmenu (fwiw you should really be using RCM+AMS - nx-hbl is obsolete).

**Comment by napier2022** [comment]
i was hoping to avoid RCM method, but I suppose that is the only path, thank you for confirming.
