### ISSUE TITLE
Error 2347-0003

### ISSUE THREAD

**Issue by rogerwilco84** [switchbrew/nx-hbmenu#159]
Attempt to launch apps from Hb menu title crashes immediately with the above error. 

Launching from applet mode album icon no issue.

I have reinstalled atmosphere sigpatches etc and deleted and replaced hbmenu.nro with no luck

**Comment by yellows8** [comment]
Sigpatches are not supported - only launching via [AMS](https://github.com/Atmosphere-NX/Atmosphere/blob/master/docs/components/modules/loader.md#homebrew-support) title-takeover is supported.
