### ISSUE TITLE
Unable to launch apps wihin hbmenu

### ISSUE THREAD

**Issue by chrisc25** [switchbrew/nx-hbmenu#161]
Hello, apps launch Ok from the gallery icon.  
When I load the hbmenu app from the main menu; it opens and I see all available apps.  But every app withint I try to load from fails and causes a error:
 
2347-0003 (0x75b)
Program: 0500000000010000
Firmware 16.0.1 (Atmosphere 1.5.5-master-4fe9a89ab)

**Comment by WinterMute** [comment]
What do you mean "load the hbmenu app from the main menu"?

**Comment by WinterMute** [comment]
Closing due to lack of response.
