### ISSUE TITLE
Errors when I compile the project

### ISSUE THREAD

**Issue by Kelvao** [switchbrew/nx-hbmenu#165]
Hi, im having this two errors when i try to compile.

![image](https://github.com/switchbrew/nx-hbmenu/assets/32245417/193035ef-c1c6-49b1-b498-41d7934ba2b9)

Im already using devkitpro for switch-dev and installed all pacman packages

**Comment by yellows8** [comment]
This requires libnx changes which are not yet available in a libnx release.
