### ISSUE TITLE
opening homebrew crashes atmosphere

### ISSUE THREAD

**Issue by 1994mazda** [switchbrew/nx-hbmenu#171]
whenever i open any thing home brew store or any game  it crashes atmosphere 

program 01000000000000014   error code 2162-0002 (0x4a2)  these are the errors any ideas what I should do to to fix it ? I am on latest firmware and am using a lite

**Comment by yellows8** [comment]
Remove all custom sysmodules from SD `/atmosphere/contents`.

**Comment by 1994mazda** [comment]
ok ill try that thxs

**Comment by 1994mazda** [comment]
how do I tell which ones to get rid of ?

**Comment by 1994mazda** [comment]
ok I fixed it but had to remove the whole  folder
