### ISSUE TITLE
Add 19.0.0 support 

### ISSUE THREAD

**Issue by steel101** [switchbrew/nx-hbmenu#177]

**Comment by SciresM** [comment]
This doesn't need an issue created by someone else.

**Comment by SciresM** [comment]
...I also don't think hbmenu needs any changes?

**Comment by Magicrafter13** [comment]
it black screens my switch on 19.0, and requires me to hard power cycle...

**Comment by yellows8** [comment]
@Magicrafter13 Remove anything under /atmosphere/contents/.
