### ISSUE TITLE
[Feature Request] Ability to pass files to homebrew

### ISSUE THREAD

**Issue by endrift** [switchbrew/nx-hbmenu#25]
It would be handy to be able to load files by passing them to a homebrew like you can via argv on other OSes. Maybe adding file associations alongside would make sense.

**Comment by AileenLumina** [comment]
I agree, this would be super useful for launching Python homebrew via [Pynx](https://github.com/nx-python/Pynx).

**Comment by AileenLumina** [comment]
Any update on this?

**Comment by yellows8** [comment]
What all would use this? Anything besides "... Python, JS and Lua"? Is there any use-case for passing more args than just the filepath?

**Comment by endrift** [comment]
It could work with emulators, and in fact already would work with mGBA. Passing more args than just the file path is probably not worthwhile.

**Comment by yellows8** [comment]
<code>//Icon will attempted to be loaded from the following: {$FILEPATH with extension changed to .jpg} -> icon_path config setting if it exists -> icon from app_path</code>

**Comment by yellows8** [comment]
https://switchbrew.org/wiki/Homebrew_Menu#File_Associations
