### ISSUE TITLE
Having a problem building under Arch

### ISSUE THREAD

**Issue by cspencer49519** [switchbrew/nx-hbmenu#31]
Hello, I'm running Arch:
Linux archdev.local 4.15.11-1-ARCH #1 SMP PREEMPT Mon Mar 19 18:21:03 UTC 2018 x86_64 GNU/Linux

Since the past couple days, attempting to build nx-hbmenu results in the following error for me:

``[graffix@archdev nx-hbmenu]$ make nx
make -f Makefile.nx
make[1]: Entering directory '/home/graffix/Desktop/HBL/nx-hbmenu'
netloader.c
aarch64-none-elf-gcc -MMD -MP -MF /home/graffix/Desktop/HBL/nx-hbmenu/build/netloader.d -g -Wall -O2 -ffunction-sections -march=armv8-a -mtune=cortex-a57 -mtp=soft -fPIE  -I/home/graffix/Desktop/HBL/nx-hbmenu/include -I/home/graffix/devkitPro/portlibs/switch/include -I/home/graffix/devkitPro/libnx/include -I/home/graffix/Desktop/HBL/nx-hbmenu/build -D__SWITCH__ -DVERSION=\"v2.0.0\" -c /home/graffix/Desktop/HBL/nx-hbmenu/common/netloader.c -o netloader.o 
/home/graffix/Desktop/HBL/nx-hbmenu/common/netloader.c:8:10: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
          ^~~~~~~~
compilation terminated.
make[2]: *** [/home/graffix/devkitPro/devkitA64/base_rules:19: netloader.o] Error 1
make[1]: *** [Makefile.nx:142: build] Error 2
make[1]: Leaving directory '/home/graffix/Desktop/HBL/nx-hbmenu'
make: *** [Makefile:11: nx] Error 2``

Any idea as to what could be causing this?

**Comment by notquiteapex** [comment]
as the error states, you're missing zlib. you must install the zlib portlib, see https://github.com/devkitPro/pacman-packages

**Comment by cspencer49519** [comment]
Thank you so much, I'll give that a shot, my apologies, I'm new to Arch.

**Comment by cspencer49519** [comment]
Dang it, the portlib for zlib returns 404 when attempting to download.

**Comment by cspencer49519** [comment]
My apologies, after a little tweaking of the script it works great, thanks for your time!

**Comment by WinterMute** [comment]
Please don't play around with the scripts and please don't link to this repo until the infrastructure has been released.

**Comment by cspencer49519** [comment]
I'm so sorry, I haven't linked the packages as far as I know. I had absolutely no idea this was not released. Please, again, accept my apologies.

**Comment by WinterMute** [comment]
And now you can do this https://devkitpro.org/viewtopic.php?f=13&t=8702 :)

**Comment by cspencer49519** [comment]
I see that, thank you very much, and my apologies again for jumping the gun I honestly had no idea.
