### ISSUE TITLE
nx-hbmenu won't see any apps on my SD

### ISSUE THREAD

**Issue by jrnwndr** [switchbrew/nx-hbmenu#36]
I have an SDXC Samsung EVO+ 128GB UHS-1, formatted to ExFAT. Booting CFW off of it works just fine. Even running games off of it. But nx-hbmenu tells me it doesn't see any apps on my SD.

The same goes for a Samsung branded 64GB SDXC card. I've tried a Kingston 8GB SDHC card, and that works just fine. Apps load off of it and all.

**Comment by ValliantStorme** [comment]
As a workaround until exFAT works, try formatting your SD card as FAT32

**Comment by jrnwndr** [comment]
Yes, I checked to be sure. I was using a different sd card for homebrew that worked just fine. I copied the files over to my main SD when CTCaer’s Samsung MicroSD compatible payload was released, so I could use one SD card for both games and homebrew.

**Comment by fincs** [comment]
Can you copy ftpd as hbmenu.nro and see what's visible on the SD card?

**Comment by CTCaer** [comment]
What about the folders and files attributes?
Horizon OS, has a bug that if a files or folder has the "archive" bit on, it does not see it.
Normally happens when you use windows for migrating to a new sd card.

If that's the case, you can disable it by unticking the "Folder/File is ready for archiving".

**Comment by jrnwndr** [comment]
It's fixed now. I redownloaded the sdfiles.zip, put ftpd as hbmenu.nro. Ftpd started up fine. I then proceeded to put the original hbmenu back, and put some nro's in my switch folder. Again, worked fine.

I think it had something to do with the file attributes like CTCaer said. I did this all from a mac though.

**Comment by cojuelodevil** [comment]
I'm having the same issue, can you please explain in more details how you fix it?, I'm using mac to

**Comment by yellows8** [comment]
#46

**Comment by djh816** [comment]
I had success with just removing the archive bit via "sudo chflags -R arch /Volumes/SDNAME/" and then doing a "sudo dot_clean -mn /Volumes/SDNAME/".

**Comment by pedrobacchini** [comment]
worked perfectly as djh816 explained thank you very much.

**Comment by Elliot0532** [comment]
> I had success with just removing the archive bit via "sudo chflags -R arch /Volumes/SDNAME/" and then doing a "sudo dot_clean -mn /Volumes/SDNAME/".

Hey there, I still don't know what to do. 


➜  ~ sudo chflags -R arch /Volumes/SDNAME/
Password:
Sorry, try again.
Password:
chflags: /Volumes/SDNAME/: No such file or directory
➜  ~ sudo dot_clean -mn /Volumes/SDNAME/
Failed trying to change dir to /Volumes/SDNAME/
Bad Pathname: No such file or directory

and this is how it works on my terminal.

**Comment by deadair3210** [comment]
You need to replace sdname with the mountpoint of the SD card. Replace SDNAME with the name of the drive as it appears in Finder

**Comment by Elliot0532** [comment]
> You need to replace sdname with the mountpoint of the SD card. Replace SDNAME with the name of the drive as it appears in Finder

LOL, it works. I was almost ready to copy everything from the SD card out and reformat it. Thanks so much.

**Comment by djh816** [comment]
Per mod edit on my original comment, better to target this directly at switch directory. For example:

sudo chflags -R arch /Volumes/SDNAME/switch

(replace "SDNAME" with the name of your volume that you see in Finder on mac)

**Comment by evelynmatson** [comment]
Does anyone have any other suggestions if this doesn't work? I'm on macOS and have done `sudo chflags -R arch switch` from within the switch sd card volume, then `sudo dot_clean -mn /Volumes/SWITCH`. I even went into Hekate and did unset archive bit. Homebrew still shows nothing.

If it's helpful, I managed to open NX-shell and tried to go into the switch folder, and it shows nothing there (not even 'parent folder'!). The permissions on the switch folder looked different from the atmosphere folder when I checked on NX-Shell, but when I put the SD card back on my mac to try and change that they both had permissions wide open. I'm also getting a "fswrite nx-shell lastdir failed 202" kind of error from NX-Shell each time I try to open a directory in it, but after tapping ok it opens just fine.

**Comment by yellows8** [comment]
Another option is to delete /switch, let hbmenu automatically create it during startup, then copy {whatever} to /switch.

**Comment by evelynmatson** [comment]
Thanks for the suggestion! I renamed the /switch folder to '/bad switch', but then hbmenu didn't make a new /switch.

**Comment by CarGot** [comment]
please check the name of your SD card - if it is named "SWITCH", try to rename it, e.g. to "NSW". This helped instantly for me...

**Comment by evelynmatson** [comment]
> please check the name of your SD card - if it is named "SWITCH", try to rename it, e.g. to "NSW". This helped instantly for me...

This is an interesting idea! Thank you as well.

**Comment by fincs** [comment]
Locking this thread because it has pretty much run its course. If all, it looks like it is *yet another bug* in Nintendo's FAT filesystem driver.
