### ISSUE TITLE
nxlink gets confused if console is not connected to network

### ISSUE THREAD

**Issue by misson20000** [switchbrew/nx-hbmenu#37]
If a console is not connected to any network and Y is pressed to start the nxlink server, after a certain timeout (30-60 seconds, not sure how long exactly) a malformed error dialog will appear. Perhaps worth noting is that selecting different homebrew applications changes the text on the dialog.

![Malformed error dialog](https://i.imgur.com/SPYZQLC.jpg)

**Comment by yellows8** [comment]
Latest hbmenu+libnx git?

**Comment by misson20000** [comment]
Hmm, I don't know which commit my hbmenu was built from. It brands itself as 2.0.0. I'll build and try latest when I have time.

**Comment by yellows8** [comment]
Did you test this yet?

**Comment by misson20000** [comment]
Seems to be fixed.
