### ISSUE TITLE
shorter homebrew development cycle (load NROs over network/USB)

### ISSUE THREAD

**Issue by misson20000** [switchbrew/nx-hbmenu#4]
It would be great to be able to load NROs over the network or over USB instead of putting them on an SD card. This cycle really isn't giving me a good time:

1. compile
2. pop SD card out of console
3. insert SD card into workstation's SD card reader
4. mount SD card
5. copy binaries
6. unmount SD card
7. pop into console
8. run network test
9. hit run
10. hit album button

**Comment by yellows8** [comment]
Yeah, Switch version of 3dslink would be nice.

**Comment by fincs** [comment]
+1
nxlink needs to be a thing.

**Comment by x43x61x69** [comment]
@fincs The ftpd won't be as good at current state of homebrew, as the Wifi won't be stable when we are hijacking the `ctest.cdn.nintendo.net`.

**Comment by Mafiacoding** [comment]
Wifi keeps breaking up.

**Comment by yellows8** [comment]
ebced71ec35e0de4fcb976039a63c8a9ceb0cad6
