### ISSUE TITLE
Switch OS 5.1.0 breaks homebrew menu?

### ISSUE THREAD

**Issue by peter17ji** [switchbrew/nx-hbmenu#44]
https://www.reddit.com/r/SwitchHaxing/comments/8nu0te/warning_homebrew_menu_wont_turn_on_after_updating/ As rumors go, Switch OS 5.1.0 breaks homebrew menu's functionality.

**Comment by fincs** [comment]
Unrelated to nx-hbmenu.

https://twitter.com/SciresM/status/1002062352387260418

Basically, you need to use an up to date build of [nx-hbloader](https://github.com/switchbrew/nx-hbloader).
