### ISSUE TITLE
Should this work if the card is ExFAT formatted?

### ISSUE THREAD

**Issue by BrianGilbert** [switchbrew/nx-hbmenu#46]
My card works in stock mode, but when I launch CFW and try to access homebrew launcher it says that the switch directory can't be found.

**Comment by BrianGilbert** [comment]
For anyone else having this issue:

Remove the archive bit on files on the card and it will work
https://www.computerworld.com/article/2598081/data-center/the-windows-archive-bit-is-evil-and-must-be-stopped.html

https://www.computerhope.com/forum/index.php?topic=100400.0

I did it from explorer on a windows VM.

**Comment by BrianGilbert** [comment]
It would be great if this can be fixed in HBL

**Comment by CTCaer** [comment]
libnx depends on the fs sysmodule and cannot change it.

This can be fixed via a future switch update or a "custom firmware".

**Comment by ezioruan** [comment]
@AnalogMan151   i run the command and still not  see any apps.
Is there a way to check if the files on sd card is valid(with arch)?

**Comment by aforty** [comment]
@AnalogMan151's fixed worked for me.

This *really* should be mentioned in the instructions somewhere. Most people are not going to know to check GitHub issues, let alone ones that are closed to stumble upon this fix/workaround.

**Comment by Mamotromico** [comment]
It seems I'm stuck with this problem. I'm trying to setup a windows vm to try the op solution, and I don't have a mac available. Anyone have a suggestion for a linux user?

**Comment by Shuttleu** [comment]
@AnalogMan151 Using that method does allow the files to be seen in hbmenu, however any games installed to the SD card will not work. All games that were installed and future games installed to the SD card throw an error when trying to launch them.

I would recommend running this instead
`sudo chflags -R arch /Volumes/SDCARD/switch`
Once again, replacing SDCARD with the volume name of your SD card

**Comment by Mamotromico** [comment]
By the way, Hekate has a tool to clear archive bits on all sd files. Workaround for those stuck on this.

**Comment by danxster** [comment]
This worked for me: sudo chflags -R arch /Volumes/SDCARD/switch

**Comment by Knight1** [comment]
I unset all archive bits but the switch still does not find any nro's :( 

Any further ideas? I tested many releases, downloaded it from sdfiles, unset the bits with Hereke and macOS.

**Comment by idolpx** [comment]
> For those one macOS, you can run this command in Terminal to fix the archive bit and get your homebrew to show:
> `sudo chflags -R arch /Volumes/SDCARD`
> 
> Be sure to change SDCARD to whatever your card's volume name is.

Worked for me too!  Thanks!

**Comment by Knight1** [comment]
I am very confused. 
32GiB SD card -> no problem
200GiB SD card -> nothing found. 

But when I go back to the backup files which was not found either are now displayed. So I can start every app when they are not in the switch folder. Any ideas?

**Comment by adamarsx** [comment]
> I am very confused.
> 32GiB SD card -> no problem
> 200GiB SD card -> nothing found.
> 
> But when I go back to the backup files which was not found either are now displayed. So I can start every app when they are not in the switch folder. Any ideas?
> Any yes of course I cleared the Archive bit.

Using a 128GiB SD and having the same problem, currently running all nro files from the root of my SD card as hbmenu cannot open /switch

**Comment by WinterMute** [comment]
> > I am very confused.
> > 32GiB SD card -> no problem
> > 200GiB SD card -> nothing found.
> > But when I go back to the backup files which was not found either are now displayed. So I can start every app when they are not in the switch folder. Any ideas?
> > Any yes of course I cleared the Archive bit.
> 
> Using a 128GiB SD and having the same problem, currently running all nro files from the root of my SD card as hbmenu cannot open /switch

Can you try deleting the switch folder on your sd card then let hbmenu recreate it, see if that changes anything? Can delete folder on your PC or via ftpd - hbmenu should create the folder next time it's run.

**Comment by vin047** [comment]
Reformatting the microSD card with a different partition name ("UNTITLED"), copying all files over, then running chflags command, fixed everything for me - previously had named the partition "SWITCH".

I tried all the recommended steps above (chflags, FAT32, hekate remove archive bit option) **without the partition name change**, but apps were still failing to show up. Also tried @WinterMute suggestion, but hbmenu didn't even recreate the directory.

**Comment by adamarsx** [comment]
If I copy all the files over to my Mac and then back to my SD will my games stop working? I don't want to lose my saves and installed games

**Comment by Knight1** [comment]
@vin047 THANKS fixed it. Any idea from the developers? @fincs https://github.com/switchbrew/nx-hbmenu/issues/81 the /switch was not recreated too. 

@adamarsx If you do not touch the Nintendo folder. But keep in mind that you need a backup app to backup the saves. They are on the NAND from the switch and not the sd card.

**Comment by gingerbeardman** [comment]
The archive bit was also the issue for me

**Comment by tobsn** [comment]
**OSX!**

Remove the ._* quarantine file from root:
`rm -rf /Volumes/SDCARD/._*`

Then remove the archive bits and clean all files and folders from any attributes:
`sudo chflags -R arch /Volumes/SDCARD`
`sudo xattr -rc /Volumes/SDCARD`

**Comment by gingerbeardman** [comment]
FWIW @tobsn even after doing that I continued to have problems on Switch, so I eventually reformatted as FAT32

**Comment by rschweda** [comment]
> **OSX!**
> 
> Remove the ._* quarantine file from root:
> `rm -rf /Volumes/SDCARD/._*`
> 
> Then remove the archive bits and clean all files and folders from any attributes:
> `sudo chflags -R arch /Volumes/SDCARD`
> `sudo xattr -rc /Volumes/SDCARD`

With latest Mac OS X Mojave I had to give my terminal explicit permission for deleting the Spotlight files like described here: https://bit.ly/2JhLTp0 

After that it worked fine with your approach combined with the archive flag solution described by AnalogMan. Thank you.

**Comment by jesusvallez** [comment]
And emummc or nintendo folder? I got an error applying archive bit to all my microsd

**Comment by ulao** [comment]
> @AnalogMan151 Using that method does allow the files to be seen in hbmenu, however any games installed to the SD card will not work. All games that were installed and future games installed to the SD card throw an error when trying to launch them.

This is my issue however I never changed any flags. If I install to the nand they work but sd all do this. If I install from the the OS they work fine, its just installing in the HBmenu that does not work. Would change my flags help me? If so how does one run linux commands? I there a console nro?

**Comment by cerezo074** [comment]
From Mohave 10.14.5, I've tried these things: 

1. @vin047, [Change name of the volume](https://github.com/switchbrew/nx-hbmenu/issues/46#issuecomment-455945705)
2. @tobsn, [Last step gave me an error, I think is not necessary](https://github.com/switchbrew/nx-hbmenu/issues/46#issuecomment-468794365)

**Comment by baptisteArnaud** [comment]
> sudo chflags -R arch /Volumes/<SDCARD>

if your card is exFAT formatted

> Reformatting the microSD card with a different partition name ("UNTITLED")

if FAT32

I'm not sure to understand why.

**Comment by deadair3210** [comment]
If you are talking about why format from exfat to fat32, it's due to ninty's exfat filesystem driver being a steaming pile of garbage

**Comment by baptisteArnaud** [comment]
I'm talking about why changing the partition name resolves the problem

**Comment by deadair3210** [comment]
Aah, sorry

**Comment by yellows8** [comment]
Regarding partition-name: #97

**Comment by antonsteenvoorden** [comment]
I used this [guide](https://switch.homebrew.guide/emummc/mac) to create the partitions, and it failed to read /switch (I'm using a 128GB samsung microSD which I think can only be formatted as exFAT)
Using `sudo chflags -R arch /Volumes/SWITCH/switch` did not solve my issue. 
Then as @vin047 suggest I changed the name using the following command:
```diskutil rename SWITCH NSW```

Worked like a charm. No need to re-format!

**Comment by fincs** [comment]
Locking this thread because it has pretty much run its course. Nintendo's exFAT filesystem driver is known to be buggy; and in addition it looks like it has bugs with folders having the same name as the partition label. There's nothing we can do here.
