### ISSUE TITLE
gfxInitDefault Break() called. 010000000000002d

### ISSUE THREAD

**Issue by jarulo** [switchbrew/nx-hbmenu#49]
After relaunching hbmenu about 30 times, the call viOpenDisplay will fail inside the vi module with a Break.

**Comment by jarulo** [comment]
With relaunching is meant without restarting hbmenu as applet (so just 30 times hbmenu NRO reload)

**Comment by yellows8** [comment]
"Break" what?

**Comment by yellows8** [comment]
Move to nx-hbloader with more details.
