### ISSUE TITLE
hbmenu crash on EDEV Switch

### ISSUE THREAD

**Issue by RyuSeisuke1992** [switchbrew/nx-hbmenu#52]
The hbmenu starts vie album icon keeps crashing on the DevKit Console. @SciresM sumption that "There´s probably some interface responding with an unexpected value on dev" 
Is there a way to make the menu on EDEV work?
If you need some dumping files for the solution, please let me know.
Info: My Switch is a EDEV DevKit console an the Firmware is 4.1.0.
![img_1803](https://user-images.githubusercontent.com/24828026/43542135-7eefc3d6-95cc-11e8-9d21-72fca7eecd1b.JPG)
![img_1802](https://user-images.githubusercontent.com/24828026/43542137-7f215392-95cc-11e8-8478-d786a08e90ab.JPG)

**Comment by yellows8** [comment]
What "CFW"/whatever are you using?

**Comment by RyuSeisuke1992** [comment]
Hekate CTCaer (Fork) newest version!

**Comment by yellows8** [comment]
That fatal-error is thrown by a sysmodule not homebrew. Do you see anything displayed after launching the applet and before the fatal-error?

**Comment by RyuSeisuke1992** [comment]
No, no conspiracies.

**Comment by yellows8** [comment]
what

**Comment by RyuSeisuke1992** [comment]
I mean, i see not displayed after launching the applet and before the fatal-error. Everything was normal until the crash. The nx-hbmenu works for two seconds, then it crashes.

**Comment by yellows8** [comment]
So you do see a blank screen with buttons prior to the fatal-error?

**Comment by RyuSeisuke1992** [comment]
I don't know, I see the hbmenu with the apps for a short time and then crash it (see photo above)
Want me to show it on video?

**Comment by yellows8** [comment]
yes

**Comment by RyuSeisuke1992** [comment]
okay, here the upload on gdrive:

https://drive.google.com/open?id=1hQGshnjsZ8PSxSnQUgnHFyZlr8j56hkc

**Comment by yellows8** [comment]
hbmenu can't cause random fatal-errors like that, so I assume it's "CFW" related.

**Comment by CTCaer** [comment]
Try my sd attributes fix (switch folder).
If that doesn't work, make sure that the files are not corrupted or such.

But I believe the problem comes from an incompatibility with the homebrew. It's possible to crash a sysmodule. If that's not the case try the various atmo revisions out in the wild (with only sm/loader).

**Comment by RyuSeisuke1992** [comment]
no matter what I try, it just doesn't work @CTCaer. When I try to boot Atmo, all I get is a red screen.
@yellows8 @CTCaer You know, who could help me here?

**Comment by RyuSeisuke1992** [comment]
?

**Comment by yellows8** [comment]
Can you move this to the github repo for the "CFW" you're using, or atmo* repo?

**Comment by aveao** [comment]
@RyuSeisuke1992 keep in mind that the serial in both the error screen and the bottom of switch is visible in that video. I recommend censoring those parts somehow.
