### ISSUE TITLE
unable to use nxlink

### ISSUE THREAD

**Issue by SegFault42** [switchbrew/nx-hbmenu#53]
I'm trying to launch homebrew with nxlink.

I've compiled the source code. 

When i launch hbmnu and i press Y, and i execute this command :

` cat NX-Shell.nro | nc 192.168.42.203 28280`

i have the following error : 

![img_20180813_205604](https://user-images.githubusercontent.com/9384676/44054672-88dbb51e-9f43-11e8-8b90-7cdb9ff12d3f.jpg)

**Comment by yellows8** [comment]
http://switchbrew.org/index.php?title=Homebrew_Menu#Netloader

**Comment by SegFault42** [comment]
Thank you ! :+1:
