### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by yellows8** [switchbrew/nx-hbmenu#6]
Probably should add support for themes eventually, but need to determine how to handle it.

**Comment by StevenMattera** [comment]
I was wondering if you started work on this, if not is it okay I pick this up? Did you have any ideas in mind for features? 

- Ability to set the colors in a (INI, JSON, YML) file?
- Ability to select from themes inside of hbmenu?
- Ability to have a background image?
- Ability to theme the folder icon, and invalid icon?
- Ability to hide the gradient bottom bar and waves?

**Comment by yellows8** [comment]
That's fine - use libconfig. Never started implementing {anything config related}.

**Comment by yellows8** [comment]
@StevenMattera Last+only commit for this on your branch was 2 months ago, did you stop working on it?
