### ISSUE TITLE
Can't see any Homebrew 

### ISSUE THREAD

**Issue by Odissine** [switchbrew/nx-hbmenu#63]
Hello,
I put hbmenu.nro on root from my SD Card. I tried to put others .nro file on .switch/ directory ... but when I launch SX OS CFW, I go in Homebrew ... I only see hbmenu with an exclamation point. Nothing else...
When I launch hbmenu, I arrived in hbmenu but nothing there too ...
Is there an issue with last SX Os ?
![aghj7fphswgi jurn7xva](https://user-images.githubusercontent.com/10324457/45899194-764cce80-bddc-11e8-9a10-8bd8a72929aa.jpg)
![xbtpjurzsggcmto5do msa](https://user-images.githubusercontent.com/10324457/45899196-764cce80-bddc-11e8-82ff-db7885b7624d.jpg)

**Comment by TuxSH** [comment]
NROs should be under `/switch/`, not `/.switch/`

**Comment by yellows8** [comment]
exfat?

**Comment by Odissine** [comment]
I would say ./switch/ as good directory :)
Yes SD is in ExFat

**Comment by Odissine** [comment]
Folder was ok ;) the probleme wasn't the folder ...

I just needed to uncheck in Windows only Archive files for all files present in my SD card (security Option) and all is ok ...
