### ISSUE TITLE
[UI Feature Request] hbmenu redesign, make menu entries larger, less blank spaces

### ISSUE THREAD

**Issue by NightlyFox** [switchbrew/nx-hbmenu#66]
I made a quick mockup of what I think would look nice for the hbmenu. let me know what you think! i am willing to help with the redesign, not sure how the waves would work with the menu... we could do a kind of retroarch thing? except not transparent in order to keep the waves... 
![image](https://user-images.githubusercontent.com/43125910/46578439-b0fe5b80-c9c5-11e8-9967-752acbf4018b.png)

**Comment by yellows8** [comment]
That will conflict with the text already in top-right corner, and text-display will get cramped with moving it. Names shouldn't be removed from the tiles since many apps have the same icon (even your screenshot has this).
