### ISSUE TITLE
Use a different JPEG library.

### ISSUE THREAD

**Issue by yellows8** [switchbrew/nx-hbmenu#7]
Eventually a different JPEG library should be used instead of nanojpeg, since nanojpeg doesn't [support](https://github.com/switchbrew/nx-hbmenu/blob/master/common/nanojpeg.c#L37-L41) progressive/lossless JPEG.

**Comment by MehdiKhelfi** [comment]
can't you use libjpeg ?

**Comment by yellows8** [comment]
Can use the pacman package for it.

**Comment by MehdiKhelfi** [comment]
you mean that you need pacman to use libjpeg ?

**Comment by yellows8** [comment]
Install the libjpeg-turbo package with dkp-pacman ...

**Comment by MehdiKhelfi** [comment]
ah ok....

**Comment by NightlyFox** [comment]
so i replaced nanojpeg with turbojpeg and merged it with the fork of my version of the project, i am going to do another pull request for this :)
