### ISSUE TITLE
Makefile issue

### ISSUE THREAD

**Issue by urherenow** [switchbrew/nx-hbmenu#74]
Building with "make nx" is perfect.

When building with just "make" it seems like the .nro is built, but then there's something else going on and fails after showing the following (then a bunch of errors about <threads.h> )

Package freetype2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `freetype2.pc'
to the PKG_CONFIG_PATH environment variable
No package 'freetype2' found

I removed switch-freetype and reinstalled it using dkp-pacman. Also tried to install it using sudo -E dkp-pacman...

any suggestions? I am using Ubuntu, and all DKP packages are up tp date.

Edit: typing this first "export PKG_CONFIG_PATH=/opt/devkitpro/portlibs/switch/lib/pkgconfig" takes care of the first issue. Now I have to figure out the threads.h issue.

**Comment by yellows8** [comment]
That's the pc-build.

**Comment by urherenow** [comment]
I've built PC executables in my Ubuntu VM before. Just forgot what/how. I guess I'll files this as a mild annoyance then (use a script for updating/rebuilding stuff and this always errors out because of the "nx" requirement after make. Might I suggest making the PC builds the requirement instead? "make pc" for that, and simply "make" for the Switch .nro.

Either way, I'll close this. Thanks!
