### ISSUE TITLE
Bug with HBmenu auto launching within game when selecting controller.

### ISSUE THREAD

**Issue by craizen** [switchbrew/nx-hbmenu#77]
I am currently on:
SXOS v2.3 BETA
Switch OS v.5.1.0
HBmenu v3.0

When in the Overcooked 2 game menu where it asks to push "L and R" buttons on controller to continue the HBmenu will auto launch during the game and wont close. In order for me to get passed this and continue to play the game. I have to click home then go to gallery (launching SXOS), tab over to Homebrew, launch HBmenu and then close HBmenu. Otherwise I am in a constant loop of HBmenu reopening. 

It only seems to happen in the Overcooked 2 game menu and I haven't experience it elsewhere yet.

I had tried a few things hoping to fix this such as:
Reinstall game. Update game to latest version. Re-installed both DLC packs.
Use older version of HBmenu.
Use older version of SXOS.

Neither of these seem to work. Is there a temp fix for this or would anyone mind checking to see if this also happening to their game please?

**Comment by yellows8** [comment]
It's SX, can't do anything about it.

**Comment by fincs** [comment]
We do not support stolen software, especially stolen software that is geared towards piracy. Please remove all traces of SXOS from your system, install Atmosphère and try again.

**Comment by craizen** [comment]
@finds. Why jump to the conclusion that I'm stealing software? Kind of odd to make an false statement without any evidence.

**Comment by fincs** [comment]
SXOS itself consists primarily of stolen Atmosphère code, violating GPL.

**Comment by craizen** [comment]
@fincs... :| oh my. I come asking for help about hbmenu and I get someone trying to discuss sxos legality. Ugh. .. lol I'm not going to debate this.

**Comment by yellows8** [comment]
(Your issue is with SXOS itself, hence original comment)
