### ISSUE TITLE
[Suggestion] Add network connection icon

### ISSUE THREAD

**Issue by maciak** [switchbrew/nx-hbmenu#79]
Hi,
An icon showing if wifi / lan is connected would be great somewhere next to the battery as sometimes I turn FTP on when not connected and it fails with an error. Would be great to see if it's actually connected when in HBmenu :)

**Comment by yellows8** [comment]
ATM you can do this: press Y -> will display an offline message if needed.

**Comment by maciak** [comment]
Ok thats usefull for now but are there any plans for just an icon? It does not have to show the signal strength.

**Comment by yellows8** [comment]
Would need icon gfx for it.

**Comment by maciak** [comment]
Would something like this be good enough? :)
![wifi](https://user-images.githubusercontent.com/1494232/49391073-eb1c7d00-f72a-11e8-9077-19a3caa04492.png)

**Comment by yellows8** [comment]
Not sure.

**Comment by endrift** [comment]
I can make some icons if it helps. I would find this useful.

**Comment by yellows8** [comment]
@endrift sure

**Comment by endrift** [comment]
![Wifi](https://user-images.githubusercontent.com/605502/59644094-54d90300-9120-11e9-895d-4ea7dc5ab55a.png) ![No wifi](https://user-images.githubusercontent.com/605502/59644095-54d90300-9120-11e9-82ea-246b80308bf5.png) ![Airplane](https://user-images.githubusercontent.com/605502/59644096-54d90300-9120-11e9-860b-4c29c68d23af.png) ![Ethernet](https://user-images.githubusercontent.com/605502/59644097-55719980-9120-11e9-8b0e-46dda91e90d9.png)
The ethernet one turned out terrible once I scaled it down, oops.

**Comment by yellows8** [comment]
@endrift  Can you make the icons' size bigger, and include a hbmenu screenshot with the icons added?

**Comment by endrift** [comment]
How big do you want? I made these about the same size as the already existing assets I thought. Not sure about the bin files though, I was going off the .png resolution.

**Comment by fincs** [comment]
How about 24x24?

**Comment by endrift** [comment]
![Artboard 1-16](https://user-images.githubusercontent.com/605502/59797246-24b27100-9294-11e9-8e15-542014905a76.png)
![Artboard 1-24](https://user-images.githubusercontent.com/605502/59797247-254b0780-9294-11e9-9ca4-f91adbfeeaec.png)
<img width="16" alt="Artboard 1-32" src="https://user-images.githubusercontent.com/605502/59797248-254b0780-9294-11e9-97ae-fdcbeacbfc18.png">
![Artboard 2-16](https://user-images.githubusercontent.com/605502/59797249-254b0780-9294-11e9-95f9-d5ed377a0c9f.png)
![Artboard 2-24](https://user-images.githubusercontent.com/605502/59797250-254b0780-9294-11e9-90c0-813b2b4c980b.png)
<img width="16" alt="Artboard 2-32" src="https://user-images.githubusercontent.com/605502/59797251-25e39e00-9294-11e9-818a-ea6d0f507b82.png">
![Artboard 3-16](https://user-images.githubusercontent.com/605502/59797252-25e39e00-9294-11e9-9b13-c8a68ab66f6b.png)
![Artboard 3-24](https://user-images.githubusercontent.com/605502/59797253-25e39e00-9294-11e9-8d10-84c51611b32f.png)
<img width="16" alt="Artboard 3-32" src="https://user-images.githubusercontent.com/605502/59797254-25e39e00-9294-11e9-9354-8cc97da3eaba.png">
![Artboard 4-16](https://user-images.githubusercontent.com/605502/59797255-25e39e00-9294-11e9-9e03-9729743550d2.png)
![Artboard 4-24](https://user-images.githubusercontent.com/605502/59797256-267c3480-9294-11e9-8937-5d71d3bb44aa.png)
<img width="16" alt="Artboard 4-32" src="https://user-images.githubusercontent.com/605502/59797258-267c3480-9294-11e9-84af-2ab6f407d637.png">
![hbmenu-wifi](https://user-images.githubusercontent.com/605502/59797260-267c3480-9294-11e9-9552-f25be9025dfe.jpg)
for some reason the hinting broke on the resized ones. I have SVGs too.

**Comment by yellows8** [comment]
And icons for the other wifi strength values?

**Comment by endrift** [comment]
![Artboard 5-16](https://user-images.githubusercontent.com/605502/59870676-d6ac7480-934a-11e9-8d8c-a8cc7fa11d6a.png)
![Artboard 5-24](https://user-images.githubusercontent.com/605502/59870677-d6ac7480-934a-11e9-9f98-6019c8816c40.png)
<img width="16" alt="Artboard 5-32" src="https://user-images.githubusercontent.com/605502/59870678-d7450b00-934a-11e9-843a-783cd55f9cf8.png">
![Artboard 6-16](https://user-images.githubusercontent.com/605502/59870679-d7450b00-934a-11e9-9c4b-116e35117102.png)
![Artboard 6-24](https://user-images.githubusercontent.com/605502/59870680-d7450b00-934a-11e9-8f03-b33a3178bbfa.png)
<img width="16" alt="Artboard 6-32" src="https://user-images.githubusercontent.com/605502/59870681-d7450b00-934a-11e9-8c1f-7c941aacbc37.png">

**Comment by yellows8** [comment]
Can you make 24x24 versions of the power icons too?

**Comment by endrift** [comment]
![Artboard 7-16](https://user-images.githubusercontent.com/605502/59871976-a914fa80-934d-11e9-9419-eaedf8778b4b.png)
![Artboard 7-24](https://user-images.githubusercontent.com/605502/59871977-a914fa80-934d-11e9-85d2-8299f638b971.png)
<img width="16" alt="Artboard 7-32" src="https://user-images.githubusercontent.com/605502/59871978-a914fa80-934d-11e9-8a3f-a0e8bd4c6c4a.png">
![Artboard 8-16](https://user-images.githubusercontent.com/605502/59871979-a9ad9100-934d-11e9-9e4a-bb40f6548f4c.png)
![Artboard 8-24](https://user-images.githubusercontent.com/605502/59871980-a9ad9100-934d-11e9-8895-1afb0fb55bbe.png)
<img width="16" alt="Artboard 8-32" src="https://user-images.githubusercontent.com/605502/59871981-a9ad9100-934d-11e9-954f-86035c0766ad.png">
![Artboard 9-16](https://user-images.githubusercontent.com/605502/59871983-a9ad9100-934d-11e9-8cc3-49720f6c04ad.png)
![Artboard 9-24](https://user-images.githubusercontent.com/605502/59871984-a9ad9100-934d-11e9-9901-cb57e597a5e8.png)
<img width="16" alt="Artboard 9-32" src="https://user-images.githubusercontent.com/605502/59871985-a9ad9100-934d-11e9-8dc0-f9b48440ec58.png">
![Artboard 10-16](https://user-images.githubusercontent.com/605502/59871986-aa462780-934d-11e9-8625-31c6fd6236f7.png)
![Artboard 10-24](https://user-images.githubusercontent.com/605502/59871987-aa462780-934d-11e9-8461-dfcc0f7055c2.png)
<img width="16" alt="Artboard 10-32" src="https://user-images.githubusercontent.com/605502/59871988-aa462780-934d-11e9-8528-1d21a7639f10.png">
![Artboard 11-16](https://user-images.githubusercontent.com/605502/59871989-aa462780-934d-11e9-8500-0816b55a2931.png)
![Artboard 11-24](https://user-images.githubusercontent.com/605502/59871990-aa462780-934d-11e9-8168-be761d08c187.png)
<img width="16" alt="Artboard 11-32" src="https://user-images.githubusercontent.com/605502/59871991-aa462780-934d-11e9-9da8-de7520da34cb.png">
![Artboard 12-16](https://user-images.githubusercontent.com/605502/59871992-aadebe00-934d-11e9-8088-3d6c71b9cd40.png)
![Artboard 12-24](https://user-images.githubusercontent.com/605502/59871993-aadebe00-934d-11e9-8324-e7a08cc03bfc.png)
<img width="16" alt="Artboard 12-32" src="https://user-images.githubusercontent.com/605502/59871994-aadebe00-934d-11e9-9591-8f178726bbf7.png">
![Artboard 13-16](https://user-images.githubusercontent.com/605502/59871995-aadebe00-934d-11e9-9be1-21c46dcc56f1.png)
![Artboard 13-24](https://user-images.githubusercontent.com/605502/59871996-aadebe00-934d-11e9-9f91-406c300cfe56.png)
<img width="16" alt="Artboard 13-32" src="https://user-images.githubusercontent.com/605502/59871997-aadebe00-934d-11e9-8acb-906368336fdc.png">
![Artboard 14-16](https://user-images.githubusercontent.com/605502/59871998-ab775480-934d-11e9-9c82-a46a82cee81d.png)
![Artboard 14-24](https://user-images.githubusercontent.com/605502/59871999-ab775480-934d-11e9-989b-1927bbf9386b.png)
<img width="16" alt="Artboard 14-32" src="https://user-images.githubusercontent.com/605502/59872000-ab775480-934d-11e9-87ba-f9c693a3e48c.png">
![Artboard 15-16](https://user-images.githubusercontent.com/605502/59872001-ab775480-934d-11e9-985f-7bbcf19d7315.png)
![Artboard 15-24](https://user-images.githubusercontent.com/605502/59872003-ac0feb00-934d-11e9-8951-ab6b875e3f1d.png)
<img width="16" alt="Artboard 15-32" src="https://user-images.githubusercontent.com/605502/59872004-ac0feb00-934d-11e9-936e-96d84b07e1ad.png">
![Artboard 16-16](https://user-images.githubusercontent.com/605502/59872005-ac0feb00-934d-11e9-8c8f-f558f93310f1.png)
![Artboard 16-24](https://user-images.githubusercontent.com/605502/59872006-ac0feb00-934d-11e9-8062-0bcc717d7a3e.png)
<img width="16" alt="Artboard 16-32" src="https://user-images.githubusercontent.com/605502/59872007-ac0feb00-934d-11e9-881f-f8dda47e8fe3.png">
![Artboard 17-16](https://user-images.githubusercontent.com/605502/59872008-ac0feb00-934d-11e9-9e44-78e1204ea94e.png)
![Artboard 17-24](https://user-images.githubusercontent.com/605502/59872009-aca88180-934d-11e9-8416-4c3b31531968.png)
<img width="16" alt="Artboard 17-32" src="https://user-images.githubusercontent.com/605502/59872010-aca88180-934d-11e9-97dd-0445cecf03ed.png">
![Artboard 18-16](https://user-images.githubusercontent.com/605502/59872011-aca88180-934d-11e9-89ef-8a83c0a722b2.png)
![Artboard 18-24](https://user-images.githubusercontent.com/605502/59872012-aca88180-934d-11e9-9ff9-6cd6f2df42ec.png)
<img width="16" alt="Artboard 18-32" src="https://user-images.githubusercontent.com/605502/59872013-aca88180-934d-11e9-892a-3f7d23a51775.png">
![Artboard 19-16](https://user-images.githubusercontent.com/605502/59872014-aca88180-934d-11e9-8b2d-6c756163641b.png)
![Artboard 19-24](https://user-images.githubusercontent.com/605502/59872017-ad411800-934d-11e9-9e49-b2d597f67a6b.png)
<img width="16" alt="Artboard 19-32" src="https://user-images.githubusercontent.com/605502/59872018-ad411800-934d-11e9-8005-93e29b7ad126.png">
![Artboard 20-16](https://user-images.githubusercontent.com/605502/59872019-ad411800-934d-11e9-9ce2-ba807e59857c.png)
![Artboard 20-24](https://user-images.githubusercontent.com/605502/59872020-ad411800-934d-11e9-8227-e9adaed9acb0.png)
<img width="16" alt="Artboard 20-32" src="https://user-images.githubusercontent.com/605502/59872021-ad411800-934d-11e9-82fe-4f5eb33e8304.png">

**Comment by endrift** [comment]
It might be better to take 48x48 versions of all of these and downscale them to get crisper versions...so here are 48x48 versions of all them.
![Artboard 1-48](https://user-images.githubusercontent.com/605502/59872351-6f90bf00-934e-11e9-8ea2-b69194a52f75.png)
![Artboard 10-48](https://user-images.githubusercontent.com/605502/59872352-6f90bf00-934e-11e9-93ce-e45e9bc7c931.png)
![Artboard 11-48](https://user-images.githubusercontent.com/605502/59872353-6f90bf00-934e-11e9-8eee-5d282b80214d.png)
![Artboard 12-48](https://user-images.githubusercontent.com/605502/59872354-70295580-934e-11e9-94b7-3506994656ff.png)
![Artboard 13-48](https://user-images.githubusercontent.com/605502/59872356-70295580-934e-11e9-83da-964aae637dc7.png)
![Artboard 14-48](https://user-images.githubusercontent.com/605502/59872357-70295580-934e-11e9-93c1-1f484576c890.png)
![Artboard 15-48](https://user-images.githubusercontent.com/605502/59872358-70295580-934e-11e9-8b6d-e718db1928fc.png)
![Artboard 16-48](https://user-images.githubusercontent.com/605502/59872360-70295580-934e-11e9-8ca2-53f7b60b6021.png)
![Artboard 17-48](https://user-images.githubusercontent.com/605502/59872362-70295580-934e-11e9-86c2-40210b4ea5f2.png)
![Artboard 18-48](https://user-images.githubusercontent.com/605502/59872363-70c1ec00-934e-11e9-8d82-c3ed27a982e8.png)
![Artboard 19-48](https://user-images.githubusercontent.com/605502/59872364-70c1ec00-934e-11e9-8ea0-b4fc7f727e0e.png)
![Artboard 2-48](https://user-images.githubusercontent.com/605502/59872365-70c1ec00-934e-11e9-9310-7080f7fb6319.png)
![Artboard 20-48](https://user-images.githubusercontent.com/605502/59872366-70c1ec00-934e-11e9-8aa9-a7a91b89d87c.png)
![Artboard 3-48](https://user-images.githubusercontent.com/605502/59872367-70c1ec00-934e-11e9-90c3-389d161a7f99.png)
![Artboard 4-48](https://user-images.githubusercontent.com/605502/59872368-70c1ec00-934e-11e9-885c-0e717b32a0b6.png)
![Artboard 5-48](https://user-images.githubusercontent.com/605502/59872370-715a8280-934e-11e9-93d8-960d67af61b8.png)
![Artboard 6-48](https://user-images.githubusercontent.com/605502/59872372-715a8280-934e-11e9-8cf4-862554c12f57.png)
![Artboard 7-48](https://user-images.githubusercontent.com/605502/59872374-715a8280-934e-11e9-90a9-ffb6a9ad521b.png)
![Artboard 8-48](https://user-images.githubusercontent.com/605502/59872375-715a8280-934e-11e9-902e-77303ee7b8ab.png)
![Artboard 9-48](https://user-images.githubusercontent.com/605502/59872376-715a8280-934e-11e9-9945-10bbee7a5f47.png)

**Comment by yellows8** [comment]
Probably should have an icon for this: `    if (contype == NifmInternetConnectionType_Ethernet) {
        if (connectionStatus != NifmInternetConnectionStatus_Connected) return false;` (currently doesn't display an icon in that case)

**Comment by endrift** [comment]
![Artboard 4-16](https://user-images.githubusercontent.com/605502/59881838-6c54fd80-9365-11e9-8321-e69d3e9dddb5.png)
![Artboard 4-24](https://user-images.githubusercontent.com/605502/59881839-6c54fd80-9365-11e9-81b2-ee0b968ec931.png)
<img width="16" alt="Artboard 4-32" src="https://user-images.githubusercontent.com/605502/59881840-6c54fd80-9365-11e9-80c2-05a10ae06291.png">
![Artboard 4-48](https://user-images.githubusercontent.com/605502/59881842-6ced9400-9365-11e9-849c-e24ef0d3de17.png)
![Artboard 21-16](https://user-images.githubusercontent.com/605502/59881843-6ced9400-9365-11e9-8cf3-c95158779ba1.png)
![Artboard 21-24](https://user-images.githubusercontent.com/605502/59881845-6ced9400-9365-11e9-8961-049cc0e049bf.png)
<img width="16" alt="Artboard 21-32" src="https://user-images.githubusercontent.com/605502/59881847-6ced9400-9365-11e9-920e-0e3018126cc7.png">
![Artboard 21-48](https://user-images.githubusercontent.com/605502/59881849-6d862a80-9365-11e9-9ac5-db8547b0db03.png)
Included a fixed version of one of them that wound up a little broken

**Comment by yellows8** [comment]
thanks
