### ISSUE TITLE
Opening Homebrew Menu turns off the Nintendo Switch

### ISSUE THREAD

**Issue by lorenzovaquero** [switchbrew/nx-hbmenu#80]
### What's the issue you encountered?
Acessing Album (Homebrew Menu) crashes and/or turns off the Nintendo Switch.

### How can the issue be reproduced?
Start up Atmosphère from RCM and select the Album app.

### Crash report?
[When using "vanilla" Atmosphère with hbloader's hbl.nsp (turns off) (it includes a fatal_report)](https://gist.github.com/lorenzovaquero/c82175fc1598fae51be94018fbcdf0fd)

### Environment?
  - Bootloader: [Official fusee-primary.bin 0.8.2](https://github.com/Atmosphere-NX/Atmosphere/releases/download/0.8.2/fusee-primary.bin)
  - Atmosphère Release: [Official release 0.8.2](https://github.com/Atmosphere-NX/Atmosphere/releases/download/0.8.2/atmosphere-0.8.2-master-84c776f.zip)
  - hbmenu Release: [Official release 3.0.1](https://github.com/switchbrew/nx-hbmenu/releases/download/v3.0.1/nx-hbmenu_v3.0.1.zip)
  - hbloader Release: [Official release 2.0.1](https://github.com/switchbrew/nx-hbloader/releases/download/v2.0.1/hbl.nsp)
  - Additional kips: No

- Additional info about your environment:
  - Nintendo Switch on firmware **2.3.0** running Atmosphère 0.8.2 (serial XAJ7001280X) in Spanish without a linked Nintendo ID.
  - Also tried launching with Hekate bootloader, but without a difference.
  - Payloads are launched from TegraRcmGui.
  - Also tried with/without airplane mode and with/without joycons, but without a difference.
  - Using a Fat32 29.7 GB SD Card (31,902,400,512 bytes) from SanDisk.
  - Also tried opening album before/after entering sleep mode, but without a difference.

### Additional context?
Without CFW, the Album opens normally.

If I use the demo version of SX OS with the official 3.0.1 hbmenu, I can open the Album (holding R) and access the Homebrew Menu.

If I try to open the Homebrew Menu using [RajNX 0.7.5.1a](https://files.sshnuke.net/RajNXv0751a.zip), it opens successfully. And if I try to use Atmosphère 0.8.2 using the [hbmenu.nro included in RajNX 0.7.5.1a](https://files.sshnuke.net/RajNXv0751a.zip) (whose source I don't know where it is), now opening the Homebrew Menu works. However, there are some homebrew like [Tinfoil c.883e3bd](https://www.sdsetup.com/console?switch#atmosphere;atmos_musthave;atmos_bootlogo;atmos_fusee;kosmos_updater;kosmos_toolkit;atmos_sigpatch;ldn_mitm;atmos_sysftpd;noexs;atmos_sysnetcheat;appstorenx;hbmenu;edizon;checkpoint;tinfoil;retroarch;hekate;) that still crashes the Switch, leaving a black screen ([crash report](https://gist.github.com/lorenzovaquero/fc684371a31f01ad9fac11e922d0a429)).

**Comment by yellows8** [comment]
On a setup where you used 3.0.1 & was broken, can you try older hbmenu releases?

Doubt it's non-CFW related...

**Comment by lorenzovaquero** [comment]
Ok, I will try with the rest of the releases (give me a moment).

**Comment by lorenzovaquero** [comment]
Ok, with the same environment as before, with a Nintendo Switch on firmware **2.3.0** (serial XAJ7001280X) in Spanish without a linked Nintendo ID and in airplane mode (payloads are launched from TegraRcmGui):
  - Bootloader: [Official fusee-primary.bin 0.8.2](https://github.com/Atmosphere-NX/Atmosphere/releases/download/0.8.2/fusee-primary.bin)
  - Atmosphère Release: [Official release 0.8.2](https://github.com/Atmosphere-NX/Atmosphere/releases/download/0.8.2/atmosphere-0.8.2-master-84c776f.zip)
  - hbloader Release: [Official release 2.0.1](https://github.com/switchbrew/nx-hbloader/releases/download/v2.0.1/hbl.nsp)
  - Additional kips: No

Results are:
 - [1.0.0](https://github.com/switchbrew/nx-hbmenu/releases/download/v1.0.0/nx-hbmenu_v1.0.0.zip) works.
 - [2.0.0](https://github.com/switchbrew/nx-hbmenu/releases/download/v2.0.0/nx-hbmenu_v2.0.0.zip) works.
 - [3.0.0](https://github.com/switchbrew/nx-hbmenu/releases/download/v3.0.0/nx-hbmenu_v3.0.0.zip) **doesn't work** (Switch turns off after opening Album. If I tap the power button, the switch powers on). [Crash report](https://gist.github.com/lorenzovaquero/3ea56f6f34d129b69fd524d68dbd0f1f)
 - [3.0.1](https://github.com/switchbrew/nx-hbmenu/releases/download/v3.0.1/nx-hbmenu_v3.0.1.zip) **doesn't work** (Switch turns off after opening Album. If I tap the power button, the switch powers on). [Crash report](https://gist.github.com/lorenzovaquero/131c68882c7470db478c727d1cb66bdf)

Hope it helps.

**Comment by yellows8** [comment]
Have you tried running under an Application?

**Comment by lorenzovaquero** [comment]
Nope, which one do you suggest?

**Comment by yellows8** [comment]
anything

**Comment by lorenzovaquero** [comment]
On 2.0.0, RetroArch 1.7.5 works without a problem.

**Comment by lorenzovaquero** [comment]
Sorry, but I don't fully understand.

If you mean a retail installed game, currently I have none (I formatted the Switch a few days ago).

**Comment by yellows8** [comment]
or gamecard

**Comment by lorenzovaquero** [comment]
I'm sorry to tell you that I don't have any at this moment.

**Comment by lorenzovaquero** [comment]
And excuse my indiscretion, but what kind of relation do have the Homebrew Launcher and running a Game Title Application.

I mean, is there a chance of being a hardware failure or anything like that?

**Comment by yellows8** [comment]
As in running hbl under a game title via changing loader.ini.

"hardware failure" not sure

**Comment by lorenzovaquero** [comment]
Ohh, I see...

I don't know if it helps, but the homebrew apps Checkpoint 3.5.0 and ChoiDujourNX 1.0.1 both work from 2.0.0. However, Tinfoil c.883e3bd crashes the Switch (I tried enabling sigpatches).

**Comment by yellows8** [comment]
https://github.com/Atmosphere-NX/Atmosphere/issues/309#issuecomment-450161124

**Comment by lorenzovaquero** [comment]
Ok, thank you very much!
