### ISSUE TITLE
Applications are not found when in /switch

### ISSUE THREAD

**Issue by Knight1** [switchbrew/nx-hbmenu#81]
Hey!

Following problem. My 32 GiB sd card does not have the problem it is the same Samsung sd card typ.

But my 200 GiB has a crazy feature. Even after clearing the archive bit the hbmenu does not find anything inside /switch. But when I go to my ```backup_14.01.19``` folder the old applications which were not presented previously on /switch are now displayed and are starting. 

Any ideas? Because I don't have any clue and I tested so much. Bot SD cards are in ExFAT, Switch is on 6.1 and all files are latest from sdsetup.com

**Comment by fincs** [comment]
Make sure /switch does not have the Archive attribute set. That instructs HOS to treat the entire folder as a single file containing all files inside concatenated.

**Comment by Knight1** [comment]
I used the hakete ctc archive bit remover. Any ideas how to verify the archive bit while the switch is running?

**Comment by adamarsx** [comment]
I'm having the same problem, already tried using a Windows VM and the hekate archive bit remover

**Comment by fincs** [comment]
Delete your `/switch` folder and let hbmenu recreate it. Then try nxlinking ftpd to it and using it to transfer files.
