### ISSUE TITLE
[Feature Request] Folder Association

### ISSUE THREAD

**Issue by TurtleP** [switchbrew/nx-hbmenu#82]
Much like how #25 allowed for file association with homebrew, it'd be useful for some developer's applications to associate with a folder + extension. 

For example, Löve Potion would benefit greatly as users could launch a folder such as `{game}.lpnx` and it would be loaded. The best part is when the user wants to update their game files, it's easy to transfer only the files which were updated.

I can imagine a similar use case with pynx and other similar homebrew.

**Comment by yellows8** [comment]
Would the dirpath be passed for the arg?

**Comment by TurtleP** [comment]
Yeah, that would simplify the usage and allow for the programs to change directories and run the files inside them.
