### ISSUE TITLE
[Feature Request] Custom layout support 

### ISSUE THREAD

**Issue by goodwind** [switchbrew/nx-hbmenu#83]
This would be great if nx-hmenu themes do support custom layouts
Today it's really unconvinient to use it: small area for icons and 2\3 of the screen for useless description and enlarged icon of selected item

**Comment by MasterDriverRex** [comment]
Personally, I'd also like to change the order of homebrew apps; alphabetical is fine, but I only really use two (JKSV and Kosmos Toolbox), so I'd think moving them to the front of the list would be better.

Regarding the actual layout, yeah, none of the apps I've got have descriptions; they just list Author and Version, and are tiny. There's a ton of unused space that could be better utilised. Maybe two rows of apps?

**Comment by yellows8** [comment]
"but I only really use two ..., so I'd think moving them to the front of the list would be better." https://github.com/switchbrew/nx-hbmenu/releases/tag/v3.1.0 "Added support for starring ..."

**Comment by yellows8** [comment]
(^ multiple-menu-rows still not supported yet though)
