### ISSUE TITLE
i need help atmosphere eror code 2168-0002 (0x4a8)

### ISSUE THREAD

**Issue by gamingtheohd** [switchbrew/nx-hbmenu#85]
![HPWebcamPicture_0219](https://user-images.githubusercontent.com/51205032/58648615-c4728400-8312-11e9-8e2f-338e31699871.jpg)

I want to enter my cfw settings and it is saying after that this atmosphere error code 2168-0002 (0x4a8)

**Comment by yellows8** [comment]
This doesn't belong here, ask in the relevant repo for "cfw settings".
