### ISSUE TITLE
Doesn't detect homebrew or themes

### ISSUE THREAD

**Issue by friedkeenan** [switchbrew/nx-hbmenu#87]
I checked to make sure it wasn't because of the archive bit thing by clearing my archive bits using hekate and trying again with the latest build which didn't change anything, and then I used an older build which works as expected.

**Comment by yellows8** [comment]
Can you determine which commit broke it?(latest commit works fine here)

**Comment by friedkeenan** [comment]
I'm uh, not sure. This is really weird, I tried all the commits I could still build (from January 2nd onward), and none of them worked. I then tried the latest build from http://bsnx.lavatech.top/nx-hbmenu/ and it works, but all I've been doing is a fresh clone, and then doing a simple `make nx`.

Another weird thing about the broken state my hbmenu is in is that when I try to use nxlink to send stuff over, it tells me the function isn't implemented.

**Comment by friedkeenan** [comment]
Actually, I think I might've figured out the problem.

I downgraded my libnx to the latest release (I was on a more recent but not latest commit) and my build with that worked. I then updated my libnx to the latest commit, built this again, and it works. So I guess there's nothing to worry about now.
