### ISSUE TITLE
Missing zip command does not abort compilation process

### ISSUE THREAD

**Issue by BullyWiiPlaza** [switchbrew/nx-hbmenu#88]
A missing `zip` command will cause the resulting `nro` to be "corrupted" when running `make`. The only indication that something went wrong is the following:

```
linking nx-hbmenu.elf
built ... nx-hbmenu.nacp
Visiting directories...
Calculating metadata...
built ... nx-hbmenu.nro
make[1]: Leaving directory '/d/Consoles/Switch/nx-hbmenu'
make -f Makefile.pc
make[1]: Entering directory '/d/Consoles/Switch/nx-hbmenu'
gcc -Wall -O2 -g -DVERSION=\"v3.0.1-753a97e\"   `pkg-config freetype2 --cflags` pc_main/main.cpp pc_main/pc_launch.c pc_main/pc_power.c pc_main/pc_netstatus.c common/menu.c common/font.c common/language.c common/launch.c common/worker.c common/status.c common/menu-entry.c common/menu-list.c common/message-box.c common/text.c common/ui.c common/assets.c common/math.c common/theme.c common/netloader.c -lsfml-graphics -lsfml-window -lsfml-system -lstdc++ -lpthread `pkg-config freetype2 --libs` -lm -lminizip -lz -lconfig -lturbojpeg  -I. -iquote /opt/devkitpro/libnx/include -Ibuild_pc -g -o test
/bin/sh: pkg-config: command not found
/bin/sh: pkg-config: command not found
/bin/sh: gcc: command not found
make[1]: *** [Makefile.pc:17: test] Error 127
make[1]: Leaving directory '/d/Consoles/Switch/nx-hbmenu'
make: *** [Makefile:23: pc] Error 2
```
Strangely, this does not suggest that `zip` is the problem.

 A build should be aborted if the `zip` command is missing because then the following error screen will happen:
![image](https://user-images.githubusercontent.com/7620135/60402032-0436c080-9b8a-11e9-8724-444c266fa17f.png)
Maybe this small improvement can be implemented into the `Makefile` or maybe not. It's up to you to decide whether it is useful enough. This costed me quite some time to figure out.

On `Windows` I can compile with `make nx` but I had to manually download [this](http://downloads.sourceforge.net/gnuwin32/zip-3.0-bin.zip) `zip` package, extract it and add it to my `PATH`. Is this the intended way of getting the `zip` command to work? It seems like `devkitPro` should support this but I didn't find a way of accomplishing it (e.g. `pacman -S switch-zlib` did not give me the `zip` command).

**Comment by WinterMute** [comment]
try pacman -S zip ...
