### ISSUE TITLE
Improve app folder heuristic

### ISSUE THREAD

**Issue by fincs** [switchbrew/nx-hbmenu#9]
Currently, hbmenu displays folders containing a single nro named "boot.nro" or "\<foldername\>.nro" as the application itself instead of as a folder. Some users have already [failed to give their .nro files said names](https://www.youtube.com/watch?v=9AU_jxgUFfQ#t=2m36s), resulting in this behavior failing to trigger (and rendering homebrew app folders as... folders you need to manually navigate into). I propose this rule be relaxed, and all folders containing a sole nro to be shown as apps instead of folders.

**Comment by ckarcz** [comment]
It think it should just follow standard file system explorers. Those users should just not put their file in a folder.. some may want to organize single files into folders.

**Comment by yellows8** [comment]
@ckarcz There's *no* reason for hbmenu to show folder instead of app when there's only 1 app in the folder.
