### ISSUE TITLE
Unable to find NRO's only when in CFW

### ISSUE THREAD

**Issue by gRoberts84** [switchbrew/nx-hbmenu#90]
Hi there,

Now, I have to apologise as I know this is a frequent issue, however I have a feeling I have a different scenario that I wanted to raise just in case.

Using caffeine on OFW, I am able to open hbmenu successfully. This allows me to inject the fake news applet and proceed to booting into Hetake (SDSetup process.)

After creating an EmuMMC partition and booting into it, hbmenu is unable to access the `switch` folder. 

When pressing back to view the folder structure, I can see the folder but tapping/pressing A on it does nothing.

If I copy the switch folder and call it, for example, `apps`, I can navigate to the folder and see all the NRO's successfully.

I have used both Windows/OSX and hetake to resolve archive bits etc with no effect. 

SD Card is 128gb partitioned into two, 1x 30gb emummc partition, 89gb FAT32 32kb.

Am I missing anything?

**Comment by yellows8** [comment]
What's the content of switch/? Did you try recreating the switch/ directory? Are you using vanilla atmo?

**Comment by gRoberts84** [comment]
Ok, I'm an idiot. Deleted the folder, allowed hbmenu to recreate it and then copied my NRO's back in and bob's your aunty!! 

Sorry for wasting your time and thank you for your help!
