### ISSUE TITLE
Hbmenu doesnt work on yuzu switch emulator

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [switchbrew/nx-hbmenu#96]
![image](https://user-images.githubusercontent.com/18043258/61010246-d7359b00-a34b-11e9-855c-84189acdd50b.png)
[log.zip](https://github.com/switchbrew/nx-hbmenu/files/3379637/log.zip)
here are logs and an image of what happens

**Comment by fincs** [comment]
hbmenu is not designed to run under emulators. Launch homebrew nro files directly with yuzu instead.

**Comment by ReaperOfSouls1909** [comment]
ya some wont launch without it thats what the issue was for lol

**Comment by fincs** [comment]
You are not correct. hbmenu is just a graphical shell that runs on top of hbloader.
