### ISSUE TITLE
applications not found if SD card named SWITCH

### ISSUE THREAD

**Issue by pkishino** [switchbrew/nx-hbmenu#97]
I just managed to "fix" an annoying problem I had with my sd card.. Tried all kinds of things but no apps were found in /switch folder until I managed to launch ftp and see that there was a file named SWITCH (same as the SD card name)..once I renamed the SD card it worked again.
Just thought I would mention this in case someone else has this problem..

**Comment by deadair3210** [comment]
Pretty sure the switch reacts badly if you name the SD card switch, I usually just name my SD cards for consoles either with no name or with the size of the card

**Comment by lookye** [comment]
My sd card is also named "Switch" and everything works as intended.

**Comment by sacredbanana** [comment]
Why SD card is also called Switch with no issues. Maybe it doesn't like it all in uppercase

**Comment by fox34** [comment]
Can confirm. When using FAT32, the SD card label will always be uppercase. This issue/warning should be way more prominent.

**Comment by yellows8** [comment]
With what sysver? Can't repro on 9.x.

Are you sure it's not the archive-bit?

**Comment by fox34** [comment]
Simply changing the Label solved the issue for me. I am using 9.0.1.

**Comment by HookedBehemoth** [comment]
We have reports of that on AtlasNX discord too.
Renaming to anything but "SWITCH" apparently fixes it.
Boggles me tbh.

**Comment by fincs** [comment]
Are people with the issue running the exFAT variant of the firmware? This is starting to look to me like *yet another* prfile2 fiasco.
