### ISSUE TITLE
[Feature Request] Hold Direction Button = Scroll

### ISSUE THREAD

**Issue by IBNobody** [switchbrew/nx-hbmenu#98]
It would be nice if holding down a direction key would continuously scroll the menu selection rather than requiring multiple presses. This would better mirror Horizon's title selection behavior.

The following line is the line that detects if a button is pressed.

https://github.com/switchbrew/nx-hbmenu/blob/d7c37c68619501fc90180dfd1f5ca57c36b96a0f/nx_main/main.c#L200

A feature request would be to keep the line and also add a line...

`u32 held = hidKeysHeld(CONTROLLER_P1_AUTO);`

Then the following lines that move the selection might change to...

```
        if ((down & KEY_LEFT) || (held & KEY_LEFT)) move--;
        if ((down & KEY_RIGHT) || (held & KEY_RIGHT)) move++;
        if ((down & KEY_DOWN) || (held & KEY_DOWN)) move-=7;
        if ((down & KEY_UP) || (held & KEY_UP)) move+=7;
```

Some sort of delay/counter would need to be added to slow down the menu selection.

**Comment by fincs** [comment]
hidKeysDown being true implies hidKeysHeld also being true.
What we really need is a way to handle simulated repeated down messages, similar to libnds's [keysDownRepeat](https://libnds.devkitpro.org/arm9_2input_8h.html#a86a6f81db95c63f955a36cf060c81f8e) function.

**Comment by fincs** [comment]
Implemented by https://github.com/switchbrew/nx-hbmenu/commit/20c1f00972db74689ce168edbb4393e5c517c894.
