### ISSUE TITLE
[Feature Request] Display System Temperature?

### ISSUE THREAD

**Issue by Clydefrosch22** [switchbrew/nx-hbmenu#99]
Hey there,
really low priority request, but would it be possible to grab the temperature sensor data and display it in the Homebrew Menu, somewhere with the battery level and stuff?

As of now, the only way I know how to get a read on it is by rebooting into hekate, but that leaves a little time for the system to cool down and you can only check once, instead of multiple times through the same session.

Again, I know it's really not central to the Homebrew Menu and it's function, but it would be pretty convenient if it could be added.

Thanks for your time.

**Comment by deadair3210** [comment]
Would enjoy this but maybe behind a toggle to turn it off if not needed

**Comment by fincs** [comment]
If the temperature sensor data can be grabbed from within HOS, I guess implementing this could be considered.

**Comment by yellows8** [comment]
https://github.com/switchbrew/nx-hbmenu/commits/thermal
